<!DOCTYPE html>
<html>

<body>
	<table>
		<tr>
			<td colspan="2">
				<h3>Creator Course Brochure Submission</h3>
			</td>
		</tr>
		<tr>
			<td>Name</td>
			<td>
				<?= $data['name']; ?>
			</td>
		</tr>
		<tr>
			<td>Email</td>
			<td>
				<?= $data['email']; ?>
			</td>
		</tr>
		<tr>
			<td>Phone No
			</td>
			<td>
				<?= $data['phone']; ?>
			</td>
		</tr>

	</table>

</body>

</html>