<!DOCTYPE html>
<html>

<body>
	<table>
		<tr>
			<td colspan="2">
				Enroll for: 
			<?= $data['heading']; ?>
			</td>
		</tr>
		<tr>
			<td>Name: </td>
			<td>
				<?= $data['name']; ?>
			</td>
		</tr>
		<tr>
			<td>Email: </td>
			<td>
				<?= $data['email']; ?>
			</td>
		</tr>
		<tr>
			<td>Phone No: </td>
			<td>
				<?= $data['number']; ?>
			</td>
		</tr>

	

		<tr>
			<td>Date: 
			</td>
			<td>
				<?= $data['date']; ?>
			</td>
		</tr>


	
		
	

	
		
		

	</table>

</body>

</html>