<!DOCTYPE html>
<html>

<body>
	<table>
		<tr>
			<td colspan="2">
				<h3>Andaman Form Submission</h3>
			</td>
		</tr>
		<tr>
			<td>Name</td>
			<td>
				<?= $data['message']; ?>
			</td>
		</tr>
		<tr>
			<td>Email</td>
			<td>
				<?= $data['name']; ?>
			</td>
		</tr>
		<tr>
			<td>Course</td>
			<td>
				<?= $data['email']; ?>
			</td>
		</tr>

		

	


	
		
	

	
		
		

	</table>

</body>

</html>