<!DOCTYPE html>
<html>

<body>
	<table>
		<tr>
			<td colspan="2">
				<h3>Andaman Form Submission</h3>
			</td>
		</tr>
		<tr>
			<td>Name</td>
			<td>
				<?= $data['name']; ?>
			</td>
		</tr>
		<tr>
			<td>Email</td>
			<td>
				<?= $data['email']; ?>
			</td>
		</tr>
		<tr>
			<td>Course</td>
			<td>
				<?= $data['subject']; ?>
			</td>
		</tr>

		<tr>
			<td>Phone No</td>
			<td>
				<?= $data['number']; ?>
			</td>
		</tr>

		<tr>
			<td>Message
			</td>
			<td>
				<?= $data['message']; ?>
			</td>
		</tr>


	
		
	

	
		
		

	</table>

</body>

</html>