<!DOCTYPE html>
<html>

<body>

	
	<div class="banner-section" style="background: url(http://aiwer.com.au/wp-content/uploads/2023/10/Group-1.png);
	background-position: center;background-size: cover;background-repeat: no-repeat;display: grid;place-items:center; padding:50px 0;
	margin-top: -100px;">
	
	<h3 style="font-size: 36px;
			color: #fff; text-align:center; margin: 20px 0;"> Dear
		<?= $data['name']; ?>,
	</h3>
	<p style="font-size: 26px;
			color: #fff;text-align:center">
	Thank You for Downloading Our Brochure!
	</p>
	
	</div>
	<p style="text-align: center; font-size:16px; color:#000">
		We're thrilled that you've taken the time to download our brochure from our website! Thank you for your interest
		in School of Techies.
		<br><br>
		Attached to this email, you'll find the brochure you requested. We hope you find it informative and that it
		helps you learn more about what we have to offer.
		<br> <br>
		Should you have any questions or need further assistance, please feel free to reach out. We're here to provide
		you with the information you need.
		<br><br>
		Thank you once again for visiting our website and downloading our brochure. We appreciate your interest in our
		products/services.
	</p>
	<div >
	<ul style="	list-style: none;
		margin: 0;
		padding: 0;">
		<li> Best regards,</li>
		<li>
			School of Techies
		</li>
		<li>Contact:
			<a href="tel:96290 92985"> 96290 92985
			</a>
		</li>
	</ul>
	<ul style="	list-style: none;
		margin: 0;
		padding: 0;display:flex; float: right;">
		<li><a href="">
		<i class="fab fa-facebook-f fa-2x me-3" style="color: #3b5998;"></i>
		</a></li>
		<li>
			School of Techies
		</li>
		<li>Contact:
			<a href="tel:96290 92985"> 96290 92985
			</a>
		</li>
	</ul>
</div>
	

</body>

</html>